### ISSUE TITLE
如何定义编辑器的尺寸

### ISSUE THREAD

**Issue by feimenggo** [Leecason/element-tiptap#23]
输入框可以铺满屏幕或者固定高度吗？
![图片](https://user-images.githubusercontent.com/12608693/77247543-2f5bc580-6c6d-11ea-9951-57db8aa213c8.png)

**Comment by Leecason** [comment]
现在的话可以手动设置
```css
.el-tiptap-editor {
  width: 100%;
  height: 100%;
}
```

之后的话会支持 `width` 和 `height` 的 props.

或者你也可以用 `Fullscreen` 这个扩展来全屏编辑器
